## Data EDA
Explore the Santa Clara dataset

In [1]:
import pandas as pd
import numpy as np
import cv2

In [9]:
data_folder="../../data/2018-09-18"

In [20]:
!ls ../../data/2018-09-18/

0002.avi		2018-09-18_drive_0002_detections_filtered.csv
0002.csv		2018-09-18_drive_0002_detections_unfiltered.csv
0002_dataframe.csv	2018-09-18_drive_0002_sync
0002_dataframe_old.csv	2018-09-18_drive_0002_sync_BACKUP
0002_filtered_new.csv	all_frames
0002_labeled.csv	association_test.py
0003.csv		frame.py
0003_filtered_new.csv	viewer_logs
0003_labeled.csv	viewer.py

In [26]:
df_detections = pd.read_csv(f"{data_folder}/2018-09-18_drive_0002_detections_filtered.csv")
df_detections.head()

,Unnamed: 0,frame,detection_index,detection_class,detection_confidence,x1,y1,x2,y2
0,0,383,0,car,0.999386,1066,433,1280,714
1,1,384,0,car,0.998988,1064,422,1280,717
2,2,385,0,car,0.999143,1060,420,1280,720
3,3,386,0,car,0.999495,1054,422,1280,720
4,4,387,0,car,0.999538,1050,419,1280,720

In [29]:
df_lidar = pd.read_csv(f"{data_folder}/0002_dataframe.csv")
df_lidar.head()

,Unnamed: 0,frame,unix_time,elapsed_time,fps,segment,distance,amplitude,flags,dist_ft,theta_rad,x,z,x_pixels,y2_pixels
0,0,1,1.537302e+09,0.079738,12.54,0,3.304718,67.488541,1,10.842251,-0.392699,-4.149150,10.016934,227,720
1,1,1,1.537302e+09,0.079738,12.54,1,3.223022,144.673691,1,10.574221,-0.340339,-3.529748,9.967699,281,720
2,2,1,1.537302e+09,0.079738,12.54,2,3.171188,156.708267,1,10.404162,-0.287979,-2.954942,9.975715,335,720
3,3,1,1.537302e+09,0.079738,12.54,3,3.123764,190.157654,1,10.248570,-0.235619,-2.392481,9.965401,390,720
4,4,1,1.537302e+09,0.079738,12.54,4,3.098648,215.041870,1,10.166169,-0.183260,-1.852637,9.995935,444,720